version: '3.1'

services:
  api:
    container_name: nest_backend
    build: .
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - .:/home/api

  database:
    image: mysql
    container_name: nest_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}'
